version: 2.1
jobs:
  check_for_files:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: "[ -f ./slo.yml ]"
workflows:
  version: 2
  update_slos:
    jobs:
      - check_for_files
